
jobs:
  build:
    language: swift
    runs-on: macOS-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 11
      run: sudo xcode-select -switch /Users/annayatsun/Downloads/Xcode.app 
    - name: Run tests
      run: xcodebuild clean test -project "web3swift.xcworkspace" -scheme "web3swift-iOS" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
    - name: Build App
      run: xcodebuild -project "web3swift.xcworkspace" -scheme "web3swift-iOS" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
