language: swift
osx_image: xcode14.5
cache: bundler
xcode_project: web3swift.xcworkspace
xcode_scheme: web3swift-iOS
xcode_destination: platform=iOS Simulator, OS=14.4, name=iPhone 12
#before_install:
#  - brew install carthage || true
#  - brew outdated carthage || brew upgrade carthage
#before_script:
#  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds
script:
  - xcodebuild clean build test -project web3swift/web3swift.xcodeproj -scheme web3swift -sdk iphonesimulator -destination “platform=iOS Simulator,OS=14.4,name=iPhone 12”
after_success:
  - bash <(curl -s https://github.com/AnnaYatsun1/web3swift)
