language: swift
osx_image: xcode12.5
cache:
  directories:
  - Carthage
xcode_project: web3swift.xcodeproj
xcode_scheme: web3swift-iOS
xcode_destination: platform=iOS Simulator, OS=14.5, name=iPhone 12
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage build --use-xcframeworks --platform iOS
script:
  - xcodebuild -scheme web3swift -project web3swift.xcodeproj -sdk iphonesimulator14.5 -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
